### ISSUE TITLE
game won't start

### ISSUE THREAD

**Issue by Grizzly90** [ScreamingSandals/BedWars#180]
#### Describe the bug
Edit: we first thougt it only appers in combination with skywars, but the game won't start even after restart of the server. Maybe the function is only available in Paper-spigot? I striced out the text below, because its  obviously only partical the reason of the bug

~~in skywars-waiting-lobby (after joining the skywars game with /sw join) performing a "/bw join <game>".
on game-start: no one is teleported to the game, but stay the he was. in console the exception shown in the log below appears.~~

~~after leaving skywars and bedwars and rejoining bedwars afterwards the same error appear in the log and the game don't start (but game is running in the bossbar appear)~~

#### Server and plugin version
Spigot version: This server is running CraftBukkit version git-Spigot-2040c4c-933e909 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
BedWars version: v0.2.8

#### Installed plugins on server (can be obtained by `/pl`)
skywars: com.walrusone.skywarsreloaded.SkyWarsReloaded 4.3.1

#### Console log
https://pastebin.com/DxFknVSh

**Comment by mindw0rm** [comment]
I don't think that Skywars is the issue here. 
The console log indicates that the problem is a missing method World.spawnEntity with three paramters.
And indeed there is no such method in Spigot (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html), only in Paper (https://papermc.io/javadocs/paper/1.15/org/bukkit/World.html).
This is due to this recent change: https://github.com/ScreamingSandals/BedWars/commit/0a6d13477281ebf295f245508ddd22a11d9f28e9

**Comment by iamceph** [comment]
Fucking spigot, I will fix that 🙄

**Comment by Misat11** [comment]
Upgrade to 0.2.9 now
