### ISSUE TITLE
Getting kicked after seconds of starting game

### ISSUE THREAD

**Issue by RenegadeXman** [ScreamingSandals/BedWars#334]
When I start a Bedwars game with my friend we get kicked after seconds of starting the game. And we get the error in the picture I have attched
![Screenshot (248)](https://user-images.githubusercontent.com/87186903/125077356-5a895300-e104-11eb-992b-d2ee640d153d.png)

Spigot version: 1.17.1
BedWars version: BedWars-0.2.18-14

Installed plugins on server

BedWars

bStats
 
Essentials	
 
HolographicDisplays
 
LuckPerms
 
Multiverse-Core
 
Multiverse-Inventories0	
 
PluginMetrics
 
ProtocolLib

SBA
 
Vault
 
BedWars-0.2.18-14 (1).jar
 
EssentialsX-2.19.0-dev+197-5e17894.jar

EssentialsXChat-2.19.0-dev+201-cba5063.jar
 
HolographicDisplays (1).jar	
 
LuckPerms-Bukkit-5.3.48.jar
 
Multiverse-Core-4.3.0 (1).jar
 
Multiverse-Inventories-4.2.2.jar
 
ProtocolLib

SBA-1.5.3 
 
Vault.jar

The error we all receive is in the Picture

**Comment by DavyJonesSimRacing** [comment]
No expert and not sure. It might be either the server version, Java version or a plugin issue. Maybe try backing up plugins folder and then starting the server with only the basic set of plugins or those that are actually in use. Just to see if one of them is causing a conflict. Also try switching the server back to MC 1.16.4/5 as when I upgraded to 1.17.1 the score hologram in the lobby wasn't working and players were being kicked out of games due to some server error.

**Comment by zlataovce** [comment]
1.17.1 is not supported by SBA, SBW supports it only in a snapshot version

**Comment by DavyJonesSimRacing** [comment]
> 1.17.1 is not supported by SBA, SBW supports it only in a snapshot version

Noted, thanks!
