### ISSUE TITLE
[Bug]: Arena position keeps bugging

### ISSUE THREAD

**Issue by AngusAU293** [ScreamingSandals/BedWars#533]
### Bug description

I've downloaded a schematic of a bedwars map and made a void world using VoidGen and Multiverse Core called "bedwars". I then pasted in the schematic using WorldEdit, then I created a new arena by doing `/bw admin 1 add` and then selected `pos1` and `pos2` of the arena by using `/bw admin 1 pos1` and `/bw admin 1 pos2`. I then added the teams and started to set the spawns. The first spwan I added successfully, though the second one I got `Location must be placed inside the arena` error. I am sure I selected the whole map and this is very annoying.

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/p/anonymous/04f2081bb3d049b9a70eb4d4b4ef34c3

**Comment by Misat11** [comment]
Since you have not saved the arena yet, I cannot see the arena configuration in the dump, but I think you have made a mistake when setting these two positions, they set the arena border in all three axis, including Y. I guess you may have forgotten that fact, and therefore your spawners in different height are outside of this border. Please refer to the documentation: https://docs.screamingsandals.org/BedWars/latest/arena/#setting-the-arena-positions

![image](https://docs.screamingsandals.org/BedWars/latest/assets/arena_bounds.png)

**Comment by AngusAU293** [comment]
It now works out of the blue. I don't know what happened but before it wasn't.
